import os, glob

env = Environment(ENV = {'PATH':os.environ['PATH']}, 
    h22libs=os.environ['h22libs'], 
    MODELLIB=os.environ['MODELLIB'])

env.ParseConfig("root-config --glibs --cflags")
env.Append(CCFLAGS = ['-g','-std=c++11'])
env.Append(CPPPATH = ['$h22libs/include/analysis/', '$h22libs/include/database/', '$h22libs/include/io/',
		       '$h22libs/include/histogram/', '$h22libs/include/nathan/', 
		       '$h22libs/include/tools/', '$h22libs/include/config/', '$h22libs/momCorr/', '$MODELLIB/include/'])

env.Append(LIBPATH = ['$h22libs/lib/'],LIBS = ['h22'])
env.Append(LIBPATH = ['$MODELLIB/lib/'], LIBS = ['CppModel','FortranModel'])
env.Append(LIBPATH = ['$ROOTSYS/lib/'], LIBS=['Tree', 'tbb', 'Imt'])

sources = glob.glob('src/*.cxx')
# sources = ['src/fillHistograms.cxx', 'src/doCrossSection.cxx']
# sources = ['src/fillHistograms.cxx']

for target in sources:
    env.Program(target)
