#!/bin/tcsh 

source ~/.login

set parFilePath = $1 
set names       = `ls $parFilePath`

echo " Parameter files to consider.. " 

foreach f ($names)
    set name = `echo $f | cut -d'.' -f1`
    set p = `ls $parFilePath* | grep $f`

    ./../src/fit /volatile/clas12/dmriser/rootFiles/asymmetry/systematic/$name.root $p
end
